### ISSUE TITLE
DailySummary.js only reflects GMT time

### ISSUE THREAD

**Issue by hankchanocd** [jaebradley/wakatime-cli#36]
Apparently `new Date()` in node only gives GMT time, and therefore `getDailySummary.js` can only yield one standard time for all users around the world. A small suggestion here to change it to `''+new Date()` so users can get the proper output for their local time. See the thread [here](https://github.com/nodejs/node-v0.x-archive/issues/3044) on getting locale time in node for more information.

BTW, awesome work on wakatime-cli. I've been looking for a good and stylish cli for it.

**Comment by jaebradley** [comment]
Thanks for suggesting this - I am pretty busy right now but I'll see if I can get to this sooner rather than later! (I'm also open to PRs if you're into that sort've thing).

Thanks again!

**Comment by hankchanocd** [comment]
On it, though it might take me some time. Need to dig in on `Jest` first.

**Comment by jaebradley** [comment]
#47 should close this

**Comment by hankchanocd** [comment]
Thank you! So excited to see `wakatime-cli` back in my everyday workflow
