### ISSUE TITLE
Add `--editors`, `--languages` and `--projects` as options

### ISSUE THREAD

**Issue by kornicameister** [jaebradley/wakatime-cli#44]
So the idea is that I am using a wakatime setup to hide projects names. As you know it generates a lot of distinct names and the output of the command gets unreadable, like so:

![image](https://user-images.githubusercontent.com/1029674/53840625-e7eb9400-3f9a-11e9-9d79-7ea9e833521f.png)

My idea, for enhancements, is to add these options and display only the data user might be interested in ;)

**Comment by jaebradley** [comment]
@kornicameister this makes a ton of sense - I don't think I can promise a hard and fast timeline for rolling this out, but thanks for opening this issue (and as always, feel free to open PRs)!

**Comment by kornicameister** [comment]
I knew you're going to say that :1st_place_medal: .
I can't say I I don't want to issue a PR for this, but there's a lot of different things going on, so it might be problematic for me as well :(.

Anyway, I am glad that you're interested in this. However this gets in, I will be happy then :)

**Comment by kornicameister** [comment]
thx @jaebradley 
works perfectly !
