### ISSUE TITLE
command waka setup does nothing

### ISSUE THREAD

**Issue by gandarez** [jaebradley/wakatime-cli#61]
Installed for the first time and `waka setup` does nothing. After typing `waka today` was asked to input api key.

<img width="418" alt="Screen Shot 2019-09-28 at 12 23 40" src="https://user-images.githubusercontent.com/782854/65818731-d3970f00-e1ea-11e9-9fc1-85d3faa79fc7.png">

**Comment by jaebradley** [comment]
@gandarez sorry you were running into this issue!

I just merged #62 that should resolve this problem. I'll update this issue when `1.4.1` is published to `npm`.

**Comment by gandarez** [comment]
Thanks for prompt response. Please follow-up into this issue when published.

**Comment by jaebradley** [comment]
@gandarez `1.4.1` seems to work for me

![image](https://user-images.githubusercontent.com/8136030/65819047-af2c3a00-e1cc-11e9-8dd0-b0a67de79430.png)

**Comment by gandarez** [comment]
It's working. Thanks.
